---

- hosts: other
  become: yes

#  environemnt:
#      http_proxy: http://example-proxy:80/
#      https_proxy: https://example-proxy:80/

 
  vars:
    key: value

  vars_files:
    - vars/main.yml
    - vars/apache_default.yml
    - vars/apache_{{ ansible_os_family }}.yml
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted  
    - name: restart ntp
      service:
        name: chronyd
        state: restarted
  
  tasks:
    - name: Download a file
      get_url:
        url: http://ipv4.download.thinkbroadband.com/20MB.zip
        dest: /tmp
#     environment:
#        http_proxy: http://example-proxy:80/
#        https_proxy: https://example-proxy:80/



    - name: Add an environment variable to the user's shell.
      lineinfile:
        dest: "~/.bash_profile"
        regexp: '^ENV_VAR= '
        line: 'ENV_VAR=value'
      become: false     
    
    - name: Get the value of environment variable
      shell: 'source ~/.bash_profile && echo $ENV_VAR'
      register: foo
      become: false

#    - debug: msg="The variable is {{ foo.stdout }}"


    - name: Install Apache.
      yum:
        name: "{{ apache_package }}"
        state: present

    - name: Copy test config file
      copy:
        src: files/test.conf
        dest: "{{ apache_config_dir }}"
      notify: 
        - restart apache
        - restart ntp    

    - name: Maksure handlers are flushed immediately
      meta: flush_handlers 
      


    - name: Make sure Apache is started now and at boot
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: yes
          


